### ISSUE TITLE
Submit requested items to lidarr

### ISSUE THREAD

**Issue by kamilkosek** [kamilkosek/jellyplist#6]

**Comment by Anexgohan** [comment]
yes please +1 this, or if this can become the downloader for lidarr, 
also it would be awesome if this could link up with the postgres database on lidarr.

**Comment by joestump** [comment]
Seconding this. One of the fun things about Spotify is the new music it introduces you to. Would be nice if this would automatically submit artists/albums to Lidarr.

**Comment by Druidblack** [comment]
Good afternoon. While your project is in active development. In particular, integration with lidarr. I would like to ask you to pay attention to the fact that your project could work correctly with this indexer https://github.com/ad-on-is/lidarr-deemix

The musicbrainz library has little necessary information about artists and current albums (why don't they parse information from music sites). To do this, there is the above program that helps lidarr interact with deezer. But there is one problem with this program, synchronization with spotify does not work with it.  And integration with last.fm is working. I do not know what the difference between requests to services is.

Of all the above, I ask you if you can do it so that your program's queries can work with the above indexer.

**Comment by kamilkosek** [comment]
Implemented [https://github.com/kamilkosek/jellyplist/releases/tag/0.1.7](https://github.com/kamilkosek/jellyplist/releases/tag/0.1.7)
